- hosts: routers
  gather_facts: no

  tasks:
    - name: "Connectivity Check with Control machine by running ios commands"
      ios_command:
        commands:
          - show run | i hostname
          - show ip interface brief | i up

      #register: output

    #- name: show output
      #when: '"hostname" in "{{output.stdout}}"'
      #debug:
        #msg: {{output}}
