#! /usr/bin/env python3 

from netmiko import ConnectHandler

switches = ['192.168.122.10', '192.168.122.20', '192.168.122.30', '192.168.122.40']

for switch in switches:
    switch_connection = {'device_type': 'cisco_ios', 'host': switch, 'username': 'zia', 'password': 'zia123', 'ssh_config_file': '/etc/ssh/ssh_config'}
    net_connect = ConnectHandler(**switch_connection)
    print(net_connect.find_prompt())
    print("-------befor----", switch, '--------')
    print(net_connect.send_command('show run | section service'))
    net_connect.send_config_set('service password-encryption')
    print("-------after----", switch, '--------')
    print(net_connect.send_command('show run | section service'))
    
