#ansible-playbook /mnt/f/zia-net-automation/EVPN_VxLAN/3_Multi_sites/Border_Leaves_extra_config/interconnect_evpn_vxlan_domains/interconnect_evpn_vxlan_domains_palybook.yaml -i /mnt/f/zia-net-automation/EVPN_VxLAN/3_Multi_sites/Border_Leaves_extra_config/interconnect_evpn_vxlan_domains/host.yaml
- name: Interconnect_EVPN_VxLAN_domains
  hosts: Border_leaves
  gather_facts: no
  tasks:
  - name: interconnect_evpn_vxlan_domains and save
    arista.eos.eos_config:
      src: interconnect_evpn_vxlan_domains_template.j2
      save_when : changed

